[project]
name = "aces-high-core-py"
version = "0.1.0"
description = "Base library for card game logic"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest-cov>=6.1.1",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
